API worker for non-blocking HTTP requests.
reportportal/client-Python pull request #110
Opened 2020-05-13 11:01 UTC by iivanou

2020-05-14 06:47 UTC, iivanou commented
> I wonder if we better use event-based control?
> 
> * I see we already do, why do we need sentinel in this case?

No need. Agree.

2020-10-13 10:43 UTC, Scanters requested changes

2020-10-13 10:43 UTC, Scanters commented on reportportal_client/core/worker.py
> +        if cmd and cmd.is_stop_cmd():
`if cmd` case is covered in line 70 and may be removed
In general, how about calling `self._stop()` at the end of line 78: `if cmd == ControlCommand.STOP:`?

2020-10-13 10:43 UTC, Scanters commented on reportportal_client/core/worker.py
> +        if cmd == ControlCommand.STOP:
I believe we can use `if cmd.is_stop_cmd():` here

2020-10-13 10:43 UTC, Scanters commented on reportportal_client/core/worker.py
> +        self._data_queue.put((request.priority, request))
We won't need to separate priority if we implement a priority field comparator for the request (__lt__)
```
from queue import PriorityQueue


class Request:
    def __init__(self, weight=1):
        self.weight = weight

    def __lt__(self, other):
        return self.weight < other.weight

    def __str__(self):
        return f"Request<{self.weight}>"


q = PriorityQueue()

q.put(Request(2))
q.put(Request(3))
q.put(Request(4))
q.put(Request(1))
q.put(Request(4))
q.put(Request(5))

while True:
    print(q.get())
```

>>>
```
Request<1>
Request<2>
Request<3>
Request<4>
Request<4>
Request<5>
```

2020-10-13 16:24 UTC, Scanters approved these changes

2020-10-14 09:15 UTC, merged